using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class TextDisplayConclusion : MonoBehaviour
{
    [SerializeField] TextMeshProUGUI conclusion;
    [SerializeField,TextArea(1,2)] string[] texts;//Unityï¿½ï¿½Å“ï¿½ï¿½Í‚ï¿½ï¿½ï¿½stringï¿½Ì”zï¿½ï¿½
    int textNumber;//ï¿½ï¿½ï¿½Ô–Ú‚ï¿½texts[]ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é‚©
    string displayText;//ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½string
    int textCharNumber;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ú‚ï¿½displayTextï¿½É’Ç‰ï¿½ï¿½ï¿½ï¿½é‚©
    int displayTextSpeed; //ï¿½Sï¿½Ì‚Ìƒtï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½gï¿½ğ—‚Æ‚ï¿½ï¿½Ïï¿½
    bool click;//ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½
    bool textStop; //ï¿½eï¿½Lï¿½Xï¿½gï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½nï¿½ß‚é‚©
    void Update()
    {
        if (textStop == false) //ï¿½eï¿½Lï¿½Xï¿½gï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ifï¿½ï¿½
        {
            displayTextSpeed++;
            if (displayTextSpeed % 3 == 0)//ï¿½Tï¿½ï¿½Éˆï¿½ï¿½vï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ifï¿½ï¿½
            {

                if (textCharNumber != texts[textNumber].Length)//ï¿½ï¿½ï¿½ï¿½text[textNumber]ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÅŒï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½
                {
                    displayText = displayText + texts[textNumber][textCharNumber];//displayTextï¿½É•ï¿½ï¿½ï¿½ï¿½ï¿½Ç‰ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
                    textCharNumber = textCharNumber + 1;//ï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
                }
                else//ï¿½ï¿½ï¿½ï¿½text[textNumber]ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÅŒï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                {
                    if (textNumber != texts.Length - 1)//ï¿½ï¿½ï¿½ï¿½texts[]ï¿½ï¿½ï¿½ÅŒï¿½ÌƒZï¿½ï¿½ï¿½tï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½
                    {
                        if (click == true)//ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ï¿½
                        {
                            displayText = "";//ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é•¶ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                            textCharNumber = 0;//ï¿½ï¿½ï¿½ï¿½ï¿½Ì”Ôï¿½ï¿½ï¿½ï¿½Åï¿½ï¿½É‚ï¿½ï¿½ï¿½
                            textNumber = textNumber + 1;//ï¿½ï¿½ï¿½ÌƒZï¿½ï¿½ï¿½tï¿½É‚ï¿½ï¿½ï¿½
                        }
                    }
                    else //ï¿½ï¿½ï¿½ï¿½texts[]ï¿½ï¿½ï¿½ÅŒï¿½ÌƒZï¿½ï¿½ï¿½tï¿½É‚È‚ï¿½ï¿½ï¿½ï¿½ï¿½
                    {
                        if (click == true) //ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ï¿½
                        {
                            displayText = ""; //ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é•¶ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                            textCharNumber = 0; //ï¿½ï¿½ï¿½ï¿½ï¿½Ì”Ôï¿½ï¿½ï¿½ï¿½Åï¿½ï¿½É‚ï¿½ï¿½ï¿½
                            textStop = true; //ï¿½Zï¿½ï¿½ï¿½tï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½~ï¿½ß‚ï¿½
                            SceneManager.LoadScene("TutrioalAnimationGatya 1");
                        }
                    }
                }

                conclusion.text = displayText.ToString();
                //this.GetComponent<Text>().text = displayText;//ï¿½ï¿½Êï¿½ï¿½displayTextï¿½ï¿½\ï¿½ï¿½
                click = false;//ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            }
            if (Input.GetMouseButton(0))//ï¿½}ï¿½Eï¿½Xï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            {
                click = true; //ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
            }
        }
    }
}